# generos = (('Autoayuda'),
#            ('Autobiografía'),
#            ('Biografía'),
#            ('Ciencia Ficción'),
#            ('Científicos'),
#            ('Clásico'),
#            ('Comedia'),
#            ('Comic; Novela Gráfica'),
#            ('Crimen'),
#            ('Cuento'),
#            ('Detective'),
#            ('Drama'),
#            ('Ensayo'),
#            ('Fábula'),
#            ('Fantasía'),
#            ('Ficción'),
#            ('Filosofía'),
#            ('Folklore'),
#            ('Fotografía'),
#            ('Guias y Manuales'),
#            ('Historia'),
#            ('Historia Ficción'),
#            ('Horror'),
#            ('Humor'),
#            ('Leyenda'),
#            ('Libro de Texto'),
#            ('Libros de Viaje'),
#            ('Memoria'),
#            ('Misterio'),
#            ('Mitología'),
#            ('No Ficción'),
#            ('Periodismo'),
#            ('Prosa'),
#            ('Realismo Ficción'),
#            ('Técnica'),
#            ('Teología'),
#            ('Tragedia'),
#            ('Tragicomedia'))

genres = ('Self-Help',
          'Autobiography',
          'Biography',
          'Science Fiction',
          'Scientific',
          'Classic',
          'Comedy',
          'Comic; Graphic Novel',
          'Crime',
          'Short Story',
          'Detective',
          'Drama',
          'Essay',
          'Fable',
          'Fantasy',
          'Fiction',
          'Philosophy',
          'Folklore',
          'Photographs',
          'Guides and Manuals',
          'History',
          'Historical Fiction',
          'Horror',
          'Humor',
          'Legend',
          'Textbook',
          'Travel Books',
          'Memoir',
          'Mystery',
          'Mythology',
          'Nonfiction',
          'Journalism',
          'Prose',
          'Realistic Fiction',
          'Technical',
          'Theology',
          'Tragedy',
          'Tragicomedy')
