# Generated by Django 4.1.4 on 2022-12-19 21:52

from django.db import migrations, models
import django.db.models.deletion
from catalog.generators import genres


def populate_genres(apps, schema_editor):
    Genre = apps.get_model("catalog", "Genre")
    db_alias = schema_editor.connection.alias
    Genre.objects.using(db_alias).bulk_create([Genre(genre='%s' % g) for g in genres])


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_genres)
    ]
